apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
  namespace: {{ .Values.namespace }}
  labels:
    app: worker
    {{- include "aml.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: worker
      {{- include "aml.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: worker
        {{- include "aml.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: worker
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          command: ["celery", "-A", "app.tasks.celery_app", "worker", "--loglevel=info", "--concurrency={{ .Values.worker.concurrency }}"]
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: db-password
            - name: AML_DATABASE_URL
              value: {{ include "aml.databaseUrl" . | quote }}
            - name: AML_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: secret-key
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          volumeMounts:
            - name: models
              mountPath: /app/models
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-models
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-beat
  namespace: {{ .Values.namespace }}
  labels:
    app: beat
    {{- include "aml.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beat
      {{- include "aml.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: beat
        {{- include "aml.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: beat
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          command: ["celery", "-A", "app.tasks.celery_app", "beat", "--loglevel=info"]
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: db-password
            - name: AML_DATABASE_URL
              value: {{ include "aml.databaseUrl" . | quote }}
          resources:
            {{- toYaml .Values.beat.resources | nindent 12 }}
