/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTransactionsIndexRouteImport } from './routes/_authenticated/transactions/index'
import { Route as AuthenticatedCasesIndexRouteImport } from './routes/_authenticated/cases/index'
import { Route as AuthenticatedAlertsIndexRouteImport } from './routes/_authenticated/alerts/index'
import { Route as AuthenticatedAlertsAlertIdRouteImport } from './routes/_authenticated/alerts/$alertId'
import { Route as AuthenticatedCreditProfilesIndexRouteImport } from './routes/_authenticated/credit-profiles/index'
import { Route as AuthenticatedCreditRequestsIndexRouteImport } from './routes/_authenticated/credit-requests/index'
import { Route as AuthenticatedCreditAnalyticsIndexRouteImport } from './routes/_authenticated/credit-analytics/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransactionsIndexRoute =
  AuthenticatedTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCasesIndexRoute = AuthenticatedCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertsIndexRoute =
  AuthenticatedAlertsIndexRouteImport.update({
    id: '/alerts/',
    path: '/alerts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAlertsAlertIdRoute =
  AuthenticatedAlertsAlertIdRouteImport.update({
    id: '/alerts/$alertId',
    path: '/alerts/$alertId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCreditProfilesIndexRoute =
  AuthenticatedCreditProfilesIndexRouteImport.update({
    id: '/credit-profiles/',
    path: '/credit-profiles/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCreditRequestsIndexRoute =
  AuthenticatedCreditRequestsIndexRouteImport.update({
    id: '/credit-requests/',
    path: '/credit-requests/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCreditAnalyticsIndexRoute =
  AuthenticatedCreditAnalyticsIndexRouteImport.update({
    id: '/credit-analytics/',
    path: '/credit-analytics/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/alerts/$alertId': typeof AuthenticatedAlertsAlertIdRoute
  '/alerts/': typeof AuthenticatedAlertsIndexRoute
  '/cases/': typeof AuthenticatedCasesIndexRoute
  '/transactions/': typeof AuthenticatedTransactionsIndexRoute
  '/credit-profiles/': typeof AuthenticatedCreditProfilesIndexRoute
  '/credit-requests/': typeof AuthenticatedCreditRequestsIndexRoute
  '/credit-analytics/': typeof AuthenticatedCreditAnalyticsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/alerts/$alertId': typeof AuthenticatedAlertsAlertIdRoute
  '/alerts': typeof AuthenticatedAlertsIndexRoute
  '/cases': typeof AuthenticatedCasesIndexRoute
  '/transactions': typeof AuthenticatedTransactionsIndexRoute
  '/credit-profiles': typeof AuthenticatedCreditProfilesIndexRoute
  '/credit-requests': typeof AuthenticatedCreditRequestsIndexRoute
  '/credit-analytics': typeof AuthenticatedCreditAnalyticsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/alerts/$alertId': typeof AuthenticatedAlertsAlertIdRoute
  '/_authenticated/alerts/': typeof AuthenticatedAlertsIndexRoute
  '/_authenticated/cases/': typeof AuthenticatedCasesIndexRoute
  '/_authenticated/transactions/': typeof AuthenticatedTransactionsIndexRoute
  '/_authenticated/credit-profiles/': typeof AuthenticatedCreditProfilesIndexRoute
  '/_authenticated/credit-requests/': typeof AuthenticatedCreditRequestsIndexRoute
  '/_authenticated/credit-analytics/': typeof AuthenticatedCreditAnalyticsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alerts/$alertId'
    | '/alerts/'
    | '/cases/'
    | '/transactions/'
    | '/credit-profiles/'
    | '/credit-requests/'
    | '/credit-analytics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/alerts/$alertId'
    | '/alerts'
    | '/cases'
    | '/transactions'
    | '/credit-profiles'
    | '/credit-requests'
    | '/credit-analytics'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/alerts/$alertId'
    | '/_authenticated/alerts/'
    | '/_authenticated/cases/'
    | '/_authenticated/transactions/'
    | '/_authenticated/credit-profiles/'
    | '/_authenticated/credit-requests/'
    | '/_authenticated/credit-analytics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions/': {
      id: '/_authenticated/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthenticatedTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cases/': {
      id: '/_authenticated/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof AuthenticatedCasesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts/': {
      id: '/_authenticated/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AuthenticatedAlertsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts/$alertId': {
      id: '/_authenticated/alerts/$alertId'
      path: '/alerts/$alertId'
      fullPath: '/alerts/$alertId'
      preLoaderRoute: typeof AuthenticatedAlertsAlertIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/credit-profiles/': {
      id: '/_authenticated/credit-profiles/'
      path: '/credit-profiles'
      fullPath: '/credit-profiles/'
      preLoaderRoute: typeof AuthenticatedCreditProfilesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/credit-requests/': {
      id: '/_authenticated/credit-requests/'
      path: '/credit-requests'
      fullPath: '/credit-requests/'
      preLoaderRoute: typeof AuthenticatedCreditRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/credit-analytics/': {
      id: '/_authenticated/credit-analytics/'
      path: '/credit-analytics'
      fullPath: '/credit-analytics/'
      preLoaderRoute: typeof AuthenticatedCreditAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAlertsAlertIdRoute: typeof AuthenticatedAlertsAlertIdRoute
  AuthenticatedAlertsIndexRoute: typeof AuthenticatedAlertsIndexRoute
  AuthenticatedCasesIndexRoute: typeof AuthenticatedCasesIndexRoute
  AuthenticatedTransactionsIndexRoute: typeof AuthenticatedTransactionsIndexRoute
  AuthenticatedCreditProfilesIndexRoute: typeof AuthenticatedCreditProfilesIndexRoute
  AuthenticatedCreditRequestsIndexRoute: typeof AuthenticatedCreditRequestsIndexRoute
  AuthenticatedCreditAnalyticsIndexRoute: typeof AuthenticatedCreditAnalyticsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAlertsAlertIdRoute: AuthenticatedAlertsAlertIdRoute,
  AuthenticatedAlertsIndexRoute: AuthenticatedAlertsIndexRoute,
  AuthenticatedCasesIndexRoute: AuthenticatedCasesIndexRoute,
  AuthenticatedTransactionsIndexRoute: AuthenticatedTransactionsIndexRoute,
  AuthenticatedCreditProfilesIndexRoute: AuthenticatedCreditProfilesIndexRoute,
  AuthenticatedCreditRequestsIndexRoute: AuthenticatedCreditRequestsIndexRoute,
  AuthenticatedCreditAnalyticsIndexRoute: AuthenticatedCreditAnalyticsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
