"""SAR (Suspicious Activity Report) service — generates COBAC-compliant filings.

Handles:
- Loading case + transactions + KYC + alert investigation data
- Calling Claude to draft a French COBAC narrative (if not already generated by LLM agent)
- Exporting to XML (COBAC schema) and PDF
"""

import json
import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.models.alert import Alert
from app.models.case import Case, CaseTransaction
from app.models.customer import Customer
from app.models.transaction import Transaction

logger = logging.getLogger(__name__)


@dataclass
class SARData:
    """Assembled data needed to generate a SAR document."""

    case_id: str
    case_number: str
    subject_name: str
    subject_client_id: str
    filing_institution: str = "WeBank Cameroun"
    filing_date: str = field(default_factory=lambda: datetime.now(timezone.utc).date().isoformat())
    report_date_range_start: str = ""
    report_date_range_end: str = ""
    transaction_count: int = 0
    total_amount: float = 0.0
    currency: str = "XAF"
    # Narrative in French for COBAC
    narrative_fr: str = ""
    # Supporting data
    transactions: list[dict] = field(default_factory=list)
    alerts: list[dict] = field(default_factory=list)
    typology: str = ""
    risk_factors: list[str] = field(default_factory=list)


class SARService:
    """Generates SAR documents for COBAC filing."""

    def __init__(self, db: AsyncSession):
        self.db = db

    async def generate_sar_document(self, case_id: UUID) -> SARData:
        """Load case data and assemble a SARData object ready for export.

        Raises:
            ValueError: If case not found or not in SAR_FILED status.
        """
        result = await self.db.execute(select(Case).where(Case.id == case_id))
        case = result.scalar_one_or_none()
        if not case:
            raise ValueError(f"Case {case_id} not found")

        # Load case transactions
        ct_result = await self.db.execute(
            select(CaseTransaction).where(CaseTransaction.case_id == case_id)
        )
        case_txns = ct_result.scalars().all()
        tx_ids = [ct.transaction_id for ct in case_txns]

        transactions: list[Transaction] = []
        if tx_ids:
            tx_result = await self.db.execute(
                select(Transaction).where(Transaction.id.in_(tx_ids))
            )
            transactions = list(tx_result.scalars().all())

        # Load alerts for the case's client
        client_id = case.fineract_client_id or ""
        alert_result = await self.db.execute(
            select(Alert).join(Transaction, Alert.transaction_id == Transaction.id).where(
                Transaction.fineract_client_id == client_id
            ).order_by(Alert.created_at.desc()).limit(20)
        )
        alerts = list(alert_result.scalars().all())

        # Load customer
        customer_result = await self.db.execute(
            select(Customer).where(Customer.fineract_client_id == client_id)
        )
        customer = customer_result.scalar_one_or_none()
        subject_name = customer.full_name if customer else f"Client {client_id}"

        # Date range
        if transactions:
            dates = [t.transaction_date for t in transactions if t.transaction_date]
            start = min(dates).date().isoformat() if dates else ""
            end = max(dates).date().isoformat() if dates else ""
        else:
            start = end = ""

        # Best narrative: from LLM investigation report if available
        narrative_fr = ""
        typology = ""
        risk_factors: list[str] = []
        for alert in alerts:
            if alert.investigation_report:
                try:
                    report = json.loads(alert.investigation_report)
                    if not report.get("error"):
                        narrative_fr = report.get("narrative_fr", "")
                        typology = report.get("typology_match", "")
                        risk_factors = report.get("risk_factors", [])
                        break
                except (json.JSONDecodeError, TypeError):
                    pass

        # Fall back to LLM draft if no investigation report
        if not narrative_fr:
            narrative_fr = await self._draft_narrative_with_llm(
                case, transactions, alerts, subject_name
            )

        sar_data = SARData(
            case_id=str(case_id),
            case_number=case.case_number,
            subject_name=subject_name,
            subject_client_id=client_id,
            report_date_range_start=start,
            report_date_range_end=end,
            transaction_count=len(transactions),
            total_amount=sum(t.amount for t in transactions),
            narrative_fr=narrative_fr,
            typology=typology,
            risk_factors=risk_factors,
            transactions=[
                {
                    "id": str(t.id),
                    "date": t.transaction_date.date().isoformat() if t.transaction_date else "",
                    "type": t.transaction_type,
                    "amount": t.amount,
                    "currency": t.currency or "XAF",
                    "counterparty": t.counterparty_name or "",
                }
                for t in transactions
            ],
            alerts=[
                {
                    "id": str(a.id),
                    "source": a.source.value if a.source else "",
                    "risk_score": a.risk_score,
                    "title": a.title,
                }
                for a in alerts
            ],
        )
        return sar_data

    async def _draft_narrative_with_llm(
        self,
        case: Case,
        transactions: list,
        alerts: list,
        subject_name: str,
    ) -> str:
        """Call Claude to draft a French COBAC SAR narrative."""
        if not settings.anthropic_api_key:
            return (
                f"Déclaration de soupçon — Dossier {case.case_number}\n\n"
                f"[Narratif à compléter manuellement]\n"
                f"Client: {subject_name}\n"
                f"Nombre de transactions: {len(transactions)}\n"
                f"Description: {case.description or 'Non renseigné'}"
            )

        try:
            import anthropic

            client = anthropic.Anthropic(api_key=settings.anthropic_api_key)

            tx_summary = "\n".join(
                f"- {t.transaction_date.date() if t.transaction_date else 'N/A'}: {t.transaction_type} "
                f"{t.amount:,.0f} XAF → {t.counterparty_name or 'N/A'}"
                for t in transactions[:20]
            )
            alert_summary = "\n".join(
                f"- {a.title} (score={a.risk_score:.2f})" for a in alerts[:5]
            )

            prompt = f"""Tu es un expert en conformité AML pour WeBank Cameroun.
Rédige une déclaration de soupçon (DS) au format COBAC en français pour le dossier suivant:

DOSSIER: {case.case_number}
CLIENT: {subject_name}
DESCRIPTION: {case.description or "Non renseignée"}

TRANSACTIONS SUSPECTES:
{tx_summary or "Aucune transaction disponible"}

ALERTES:
{alert_summary or "Aucune alerte disponible"}

La DS doit:
1. Décrire les faits suspects de façon objective et chronologique
2. Identifier la typologie de blanchiment probable (selon les 40 recommandations GAFI)
3. Mentionner les mesures de vigilance renforcée appliquées
4. Rester factuelle — pas de conclusions définitives
5. Être rédigée en langage officiel (style administratif)
6. Faire environ 300-500 mots

Commence directement par le corps de la déclaration (pas d'en-tête)."""

            response = client.messages.create(
                model=settings.llm_model,
                max_tokens=1000,
                messages=[{"role": "user", "content": prompt}],
            )
            return response.content[0].text if response.content else ""

        except Exception as exc:
            logger.error("LLM SAR narrative draft failed: %s", exc)
            return (
                f"Déclaration de soupçon — Dossier {case.case_number}\n\n"
                f"[Erreur lors de la génération automatique: {exc}]\n"
                f"Client: {subject_name}\n"
                f"Description: {case.description or 'Non renseigné'}"
            )

    def export_to_xml(self, sar_data: SARData) -> str:
        """Serialize SAR data to COBAC-compatible XML string."""
        from xml.etree.ElementTree import Element, SubElement, indent, tostring

        root = Element("DeclarationDeSoupcon")
        root.set("xmlns:cobac", "http://cobac.org/ds/v1")
        root.set("version", "1.0")

        # Header
        header = SubElement(root, "Entete")
        SubElement(header, "NumeroDossier").text = sar_data.case_number
        SubElement(header, "DateDeclaration").text = sar_data.filing_date
        SubElement(header, "InstitutionDeclarante").text = sar_data.filing_institution
        SubElement(header, "Devise").text = sar_data.currency

        # Subject
        subject = SubElement(root, "Sujet")
        SubElement(subject, "NomComplet").text = sar_data.subject_name
        SubElement(subject, "IdentifiantClient").text = sar_data.subject_client_id

        # Period
        period = SubElement(root, "PeriodeSuspecte")
        SubElement(period, "DateDebut").text = sar_data.report_date_range_start
        SubElement(period, "DateFin").text = sar_data.report_date_range_end

        # Transactions
        txns_el = SubElement(root, "Transactions")
        txns_el.set("count", str(sar_data.transaction_count))
        txns_el.set("montantTotal", f"{sar_data.total_amount:.2f}")
        for tx in sar_data.transactions:
            tx_el = SubElement(txns_el, "Transaction")
            SubElement(tx_el, "Identifiant").text = tx.get("id", "")
            SubElement(tx_el, "Date").text = tx.get("date", "")
            SubElement(tx_el, "Type").text = tx.get("type", "")
            SubElement(tx_el, "Montant").text = str(tx.get("amount", 0))
            SubElement(tx_el, "Contrepartie").text = tx.get("counterparty", "")

        # Narrative
        narr = SubElement(root, "NarratifSuspicion")
        narr.text = sar_data.narrative_fr

        # Typology
        if sar_data.typology:
            SubElement(root, "TypologieGAFI").text = sar_data.typology

        indent(root, space="  ")
        return '<?xml version="1.0" encoding="UTF-8"?>\n' + tostring(root, encoding="unicode")

    def export_to_pdf(self, sar_data: SARData) -> bytes:
        """Generate a PDF SAR document using reportlab."""
        try:
            from io import BytesIO

            from reportlab.lib import colors
            from reportlab.lib.pagesizes import A4
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import cm
            from reportlab.platypus import (
                Paragraph,
                SimpleDocTemplate,
                Spacer,
                Table,
                TableStyle,
            )

            buffer = BytesIO()
            doc = SimpleDocTemplate(
                buffer,
                pagesize=A4,
                rightMargin=2 * cm,
                leftMargin=2 * cm,
                topMargin=2.5 * cm,
                bottomMargin=2 * cm,
            )
            styles = getSampleStyleSheet()
            title_style = ParagraphStyle(
                "Title",
                parent=styles["Heading1"],
                fontSize=14,
                spaceAfter=12,
                alignment=1,  # center
            )
            heading_style = ParagraphStyle(
                "Heading",
                parent=styles["Heading2"],
                fontSize=11,
                spaceBefore=12,
                spaceAfter=6,
                textColor=colors.HexColor("#1a3c5e"),
            )
            normal_style = styles["Normal"]
            normal_style.fontSize = 10
            normal_style.leading = 14

            story = []

            # Title
            story.append(Paragraph("DÉCLARATION DE SOUPÇON", title_style))
            story.append(Paragraph("Conformément au Règlement COBAC R-2016/01", styles["Italic"]))
            story.append(Spacer(1, 0.5 * cm))

            # Header table
            header_data = [
                ["N° Dossier:", sar_data.case_number, "Date:", sar_data.filing_date],
                ["Institution:", sar_data.filing_institution, "Devise:", sar_data.currency],
                ["Période:", f"{sar_data.report_date_range_start} → {sar_data.report_date_range_end}", "", ""],
            ]
            header_table = Table(header_data, colWidths=[3 * cm, 7 * cm, 2.5 * cm, 4 * cm])
            header_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e8f0f8")),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("PADDING", (0, 0), (-1, -1), 4),
            ]))
            story.append(header_table)
            story.append(Spacer(1, 0.5 * cm))

            # Subject
            story.append(Paragraph("1. IDENTIFICATION DU SUJET", heading_style))
            story.append(Paragraph(f"<b>Nom complet:</b> {sar_data.subject_name}", normal_style))
            story.append(Paragraph(f"<b>Identifiant client:</b> {sar_data.subject_client_id}", normal_style))
            if sar_data.typology:
                story.append(Paragraph(f"<b>Typologie GAFI identifiée:</b> {sar_data.typology}", normal_style))
            story.append(Spacer(1, 0.3 * cm))

            # Transactions summary
            story.append(Paragraph("2. RÉSUMÉ DES TRANSACTIONS", heading_style))
            story.append(Paragraph(
                f"<b>Nombre de transactions:</b> {sar_data.transaction_count} | "
                f"<b>Montant total:</b> {sar_data.total_amount:,.0f} {sar_data.currency}",
                normal_style,
            ))
            story.append(Spacer(1, 0.3 * cm))

            if sar_data.transactions:
                tx_header = ["Date", "Type", "Montant", "Contrepartie"]
                tx_rows = [tx_header] + [
                    [
                        tx.get("date", ""),
                        tx.get("type", ""),
                        f"{tx.get('amount', 0):,.0f} {tx.get('currency', 'XAF')}",
                        (tx.get("counterparty") or "")[:40],
                    ]
                    for tx in sar_data.transactions[:15]
                ]
                tx_table = Table(tx_rows, colWidths=[2.5 * cm, 4 * cm, 4 * cm, 6 * cm])
                tx_table.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a3c5e")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f8fc")]),
                    ("PADDING", (0, 0), (-1, -1), 3),
                ]))
                story.append(tx_table)
                if len(sar_data.transactions) > 15:
                    story.append(Paragraph(
                        f"<i>... et {len(sar_data.transactions) - 15} transactions supplémentaires.</i>",
                        styles["Italic"],
                    ))
                story.append(Spacer(1, 0.3 * cm))

            # Narrative
            story.append(Paragraph("3. EXPOSÉ DES FAITS SUSPECTS", heading_style))
            # Split narrative into paragraphs
            for para_text in sar_data.narrative_fr.split("\n\n"):
                para_text = para_text.strip()
                if para_text:
                    story.append(Paragraph(para_text.replace("\n", "<br/>"), normal_style))
                    story.append(Spacer(1, 0.2 * cm))

            # Risk factors
            if sar_data.risk_factors:
                story.append(Paragraph("4. FACTEURS DE RISQUE", heading_style))
                for factor in sar_data.risk_factors:
                    story.append(Paragraph(f"• {factor}", normal_style))
                story.append(Spacer(1, 0.3 * cm))

            # Footer
            story.append(Spacer(1, 1 * cm))
            story.append(Paragraph(
                f"Document généré automatiquement par WeBank AML le {sar_data.filing_date}. "
                "À compléter et signer par le responsable conformité avant transmission à la COBAC.",
                styles["Italic"],
            ))

            doc.build(story)
            return buffer.getvalue()

        except ImportError:
            raise RuntimeError(
                "reportlab is required for PDF export. Install it with: pip install reportlab>=4.0.0"
            )
